import tkinter
tk=tkinter.Tk()
tk.geometry('400x450')
tk.config(bg='black')
sas1=tkinter.StringVar()
con=tkinter.StringVar()
con1=tkinter.StringVar()
sas2=tkinter.StringVar()
sas3=tkinter.StringVar()
sas4=tkinter.StringVar()
def convert():
    try:
        import binascii
        mf = open(str(sas1.get()), 'rb')
        contents = mf.read()
        hvalue = binascii.hexlify(contents)
        mf.close()
        nf = open(str(sas2.get()), 'wb')
        nf.write(hvalue)
        nf.close()
        con.set('Success...')
        sas1.set('')
        sas2.set('')
    except:
        con.set('failure...')
def reverse():
    try:
        import binascii
        mf = open(str(sas3.get()), 'rb')
        contents = mf.read()
        hvalue = binascii.unhexlify(contents)
        mf.close()
        nf = open(str(sas4.get()), 'wb')
        nf.write(hvalue)
        nf.close()
        con1.set('success')
        sas3.set('')
        sas4.set('')
    except:
        con1.set('Failure')
l1=tkinter.Label(tk,text='File Security',fg='green',bg='black')
l1.place(x=150,y=10)
l2=tkinter.Label(tk,text='Convert...',fg='red',bg='black')
l2.place(x=10,y=50)
l3=tkinter.Label(tk,text='Reverse...',fg='red',bg='black')
l3.place(x=10,y=220)
e1=tkinter.Entry(tk,textvariable=sas1,width=10,bg='black',fg='white')
e1.place(x=60,y=90)
e2=tkinter.Entry(tk,textvariable=sas2,width=10,bg='black',fg='white')
e2.place(x=200,y=90)
b1=tkinter.Button(tk,command=convert,text='start...',bg='black',fg='yellow')
b1.place(x=150,y=150)
l11=tkinter.Label(tk,textvariable=con,fg='green',bg='black')
l11.place(x=150,y=200)
l12=tkinter.Label(tk,textvariable=con1,fg='green',bg='black')
l12.place(x=150,y=350)
e3=tkinter.Entry(tk,textvariable=sas3,width=10,bg='black',fg='white')
e3.place(x=60,y=270)
e4=tkinter.Entry(tk,textvariable=sas4,width=10,bg='black',fg='white')
e4.place(x=200,y=270)
b1=tkinter.Button(tk,command=reverse,text='start...',bg='black',fg='yellow')
b1.place(x=150,y=350)
tk.mainloop()